Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_url = "ubuntu/trusty64"

  config.ssh.insert_key = false

  # Manage /etc/hosts on host and VMs
  config.hostmanager.enabled = false
  config.hostmanager.manage_host = true
  config.hostmanager.include_offline = true
  config.hostmanager.ignore_private_ip = false

  config.vm.define :head, primary: true do |machine|
    machine.vm.provider :virtualbox do |v|
      v.name = "dask-ec2-0"
      v.customize ["modifyvm", :id, "--memory", "2048"]
    end

    machine.vm.hostname = "dask-ec2-0"
    machine.vm.network :private_network, ip: "10.10.10.100"
    machine.vm.provision :hostmanager
  end

  config.vm.define :compute do |machine|
    machine.vm.provider :virtualbox do |v|
      v.name = "dask-ec2-1"
      v.customize ["modifyvm", :id, "--memory", "2048"]
    end

    # machine.vm.synced_folder '.', '/vagrant', disabled: true

    machine.vm.hostname = "dask-ec2-1"
    machine.vm.network :private_network, ip: "10.10.10.101"
    # machine.vm.network :forwarded_port, guest: 22, host: 2222, disabled: true
    machine.vm.network :forwarded_port, guest: 22, host: 2223, id: "ssh"
    machine.vm.provision :hostmanager
  end
end
